---
title: Community Lessons
---

There are growing resources developed by Openscapes teams! 

This is the beginning of a growing list; please share others to add. You can suggest via GitHub on the right of this page - click "Edit this page" or "Report an Issue", or share your idea via Twitter (linked below the logo on the left) or email openscapes @ nceas.ucsb.edu. 

## NASA Openscapes Cloud Tutorials

The NASA Earthdata-Openscapes Mentors team and other contributors are creating open educational resources to help researchers migrate workflows to the Cloud - all available for reuse and remix.

<https://nasa-openscapes.github.io/tutorials.html>

Check out the 2021-Cloud-Hackathon materials!

## NMFS Openscapes 

The overarching vision of the NMFS Openscapes is to support scientific researchers within NOAA Fisheries by providing training in reproducible scientific workflows and platforms, facilitating collaboration across divisions in common scientific data science tasks, and providing shared "best practices" resources. Check out the NMFS R UG (R Users Group) for upcoming events and Wiki for links to resources and examples of open science at NOAA Fisheries.

<https://github.com/nmfs-openscapes>

Highlighting a few lessons by Eli Holmes and Em Markowitz:

- [Advanced GitHub Clinic](https://github.com/Openscapes/2021-noaa-nmfs/blob/main/adv-github-clinic/agenda2.md)
- [googledrive R package](https://github.com/nmfs-openscapes/GoogleDrive1#overview)
- [RVerse Tutorials](https://rverse-tutorials.github.io/), particularly [Practical R+Git Workflow for Scientists May-July 2022](https://rverse-tutorials.github.io/RWorkflow-NWFSC-2022/) by Eli Holmes
  - RVerse Tutorials is a collection of teaching materials on R and R Workflow by the Mathematical Biology Program and the Northwest Fisheries Science Center.

## Fay Lab Manual

This is the lab manual for the Fay Lab at the University of Massachusetts Dartmouth School for Marine Science and Technology.

<https://thefaylab.github.io/lab-manual/> 

Check out how they've organized this onboarding document that prospective students and postdocs have said stood out to them. Consider reusing/remixing for your own group!

[Slides from Gavin Fay's 2022 talk at NOAA Alaska Fisheries Science Center](https://docs.google.com/presentation/d/1c624mH3md8pQHiP6rJ7HPuhxDLgNB7xvONDZlUM3f64/edit#slide=id.gb6050dd30d_0_0)

## R for Excel Users

This course is for Excel users who want to add or integrate R and RStudio into their existing data analysis toolkit. It is a friendly intro to becoming a modern R user, full of tidyverse, RMarkdown, GitHub, collaboration & reproducibility.

<https://rstudio-conf-2020.github.io/r-for-excel/>

Check out the resources throughout as well - it's not only for Excel users, it's for everyone.


## Allison Horst - open educational resources

Allison Horst shares many open educational resources, including workshops and slides, at <https://www.allisonhorst.com/>: 

>"I actively work to contribute to open educational resources, including software for data science education (e.g. the [palmerpenguins](https://allisonhorst.github.io/palmerpenguins/) R dataset package), and artwork for data science & stats teachers and learners. From 2019 - 2020 I was RStudio’s first Artist-in-Residence. You can read more about my motivation in that role in [this blog post](https://www.rstudio.com/blog/artist-in-residence/), and you can find some of my R- and stats-related artwork [in this repo](https://github.com/allisonhorst/stats-illustrations)."

Allison teaches environmental data science at UCSB (see her courses at <https://ucsb-meds.github.io/>).


## Tidy Tuesday

https://www.openscapes.org/blog/2019/05/02/tidy-tuesday-coding-club/

From Nyssa: 

For our group we had 2 hour sessions (1 hour is a bit too short for more novices and 2 hours gives the more advanced students time to try really new cool things). And we have a facilitator (usually me) that just checks in with the crew every few minutes and helps when students get stuck. But, it is very informal in that everyone just shows up and codes and chats. I have done this both in a conference room and at a bar. I also usually have people put some of their works in progress or final plots on the screen to show everyone else and share their "coding wins" or ask for help from the audience. And, yes, we use the Tidy Tuesday data because then they can also share their plots and code on twitter with the community and see the awesome creativity of the broader R community as well.
