project: 
  type: book
  output-dir: docs
  
book: 
  title: "Openscapes Champions Series"
  author: "Openscapes team"
  date: "February 1st, 2022"
  description: "This is the official lesson series for the Openscapes Champions program."
  repo-url: https://github.com/openscapes/series
  repo-actions: [edit, issue]
  sharing: [twitter]
  chapters: [
  "index.Rmd",
  "overview.Rmd",
  "mindset.Rmd",
  "bsilt.Rmd",
  "team-culture.Rmd",
  "code-of-conduct.Rmd",
  "data-strategies.Rmd",
  "coding-strategies.Rmd",
  "communities.Rmd",
  "github-pub.Rmd",
  "github-issues.Rmd",
  #"case-studies.Rmd", CREATE AND LINK
  #"code-tour.Rmd", 
  #"study-groups.Rmd",
  "r-for-scicomm.Rmd", 
  "resources-that-influence.Rmd",
  "testing-ohi.Rmd"]
  

bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
number-depth: 2

format:
  html:
    css: style.css





  
