--- 
title: "Openscapes Champions Series"
author: "Julie Lowndes"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
# output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: openscapes/series
description: "This is the official lesson series for the Openscapes Champions program."
---

# Welcome {#welcome}

This book is a lesson series for the Openscapes Champions program. *It is under heavy development*.

The Openscapes Champions program is designed to meet scientists where they are and help identify incremental steps to make their data workflows more efficient and open. We've been building Openscapes from an open data science angle, but along with that comes the mindset of openness, collaboration, good intentions, and creating the culture we want in science. 

The Series is framed around [Lowndes *et al. 2017, Nature Ecology & Evolution*: Our path to better science in less time using open data science tools](https://www.nature.com/articles/s41559-017-0160). That paper is a retrospective of how a team's data workflow changed over four years; the Openscapes Series aims to help guide other labs to incrementally make progress themselves, no matter where they are starting from. The first half of the Series focuses on efficiency and open culture within the lab, and the second half is about sustained learning and bring these practices to the broader campus community.

This Series is written (and always improving) to be used as a reference, to teach, or as self-paced learning.

----

[Openscapes](https://openscapes.org) is operated by the National Center for Ecological Analysis & Synthesis ([NCEAS](https://www.nceas.ucsb.edu/)) and is being incubated by a [Mozilla](https://foundation.mozilla.org/en/) Fellowship awarded to [Julia Stewart Lowndes](http://jules32.github.io).

<!---


Before you begin, be sure you are all set up: see the prerequisites in Chapter \@ref(overview). 

Suggested breakdown for a 2-day workshop: 

|Week       |      Cohort Call Topic|      Assignment|
|:----------|----------:|----------:|
|1. Table 1    |  [Openscapes overview](#overview), [Openscapes mindset](#mindset) |  [Data Wrangling: `tidyr`](#tidyr) |
|break      |  | |
|11-12:30   | [GitHub](#github) | [Programming](#programming) |
|lunch      |  ||
|13:30-15:00 |  [Visualization: `ggplot2`](#ggplot2) | [Collaborating with GitHub](#collaborating) |
|break      |  |  |
|15:30-17:00 |  [Data Wrangling: `dplyr`](#dplyr) | Practice, [Be a champion for open data science](#champion) |




Mentee topic
Cohort Call topic
Assignment
Table 1
1. Openscapes mindset
read Lowndes et al 2017
2. Better science in less time
Seaside chat, Table 1
Lab culture
3. Lab culture
Code of conduct
4. Github for your lab
Code of conduct on Github
Coding practices
5. R community practices, packages efficiency tour


6. Mid-series check in


Community
7. Study Groups
Start a study group


8. 




9. Amplify




10. Share
--->

