# Introduction {#introduction}

Welcome. 



*In this training you will learn R, RStudio, Git, and GitHub. It's going to be fun and empowering! You will learn a reproducible workflow that can be used in research and analyses of all kinds, including Ocean Health Index assessments. This is really powerful, cool stuff, and not just for data: I made and published this book using those four tools and workflow.*

## What to expect

This is going to be a fun course.  

*The plan is to expose you to a lot of great tools that you can have confidence using in your research. You'll be working hands-on and doing the same things on your own computer as we do live on up on the screen. We're going to go through a lot in these two days and it's less important that you remember it all. More importantly, you'll have experience with it and confidence that you can do it. The main thing to take away is that there are good ways to approach your analyses; we will teach you to expect that so you can find what you need and use it! A theme throughout is that tools exist and are being developed by real, and extraordinarily nice, people to meet you where you are and help you do what you need to do. If you expect and appreciate that, you will be more efficient in doing your awesome science.*

You are all welcome here, please be respectful of one another. You are encouraged to help each other. 

Everyone in this workshop is coming from a different place with different experiences and expectations. But everyone will learn something new here, because there is so much innovation in the data science world. Instructors and helpers learn something new every time, from each other and from your questions. If you are already familiar with some of this material, focus on how we teach, and how you might teach it to others. Use these workshop materials not only as a reference in the future but also for talking points so you can communicate the importance of these tools to your communities. A big part of this training is not only for you to learn these skills, but for you to also teach others and increase the value and practice of open data science in science as a whole. 

## What you'll learn

## Data science as a mindset

- analysis_final_v2.xlsx
- Re:FWD:Fwd:Data question
- your science is not unique when it comes to data
- expect there is a way to do what you want to do
    
## Lab members as a team
        - data & workflows lab meeting “nuts and bolts”

## Communities for learning, teaching, and mentorship

    
## The Internet as an unleveraged tool for science (or intro to Julie?)
        - I don't have all the answers, but I expect them and know how to look
        - I build websites with RStudio+GitHub
            - Personal website: I link to pubs, slide decks, and interviews/media



<!---
- how to THINK about data 
    - how to think about data separately from your research questions
    - how and why to tidy data and analyze tidy data, rather than making your analyses accommodate messy data
    - how there is a lot of decision-making involved with data analysis, and a lot of creativity
- how to increase efficiency in your science
    - and increase reproducibility
    - and facilitate collaboration with others — especially Future You!
- how open science is a great benefit
    - find solutions faster
    - broaden the impact of your work
- how to learn with intention and community
    - think ahead instead of only to get a single job done now
    - the #rstats online community is fantastic. The tools we're using are developed by real people. Real, nice people. They are building powerful and empowering tools and are welcoming to all skill-levels
--->



## Emphasizing collaboration

Collaborating efficiently has historically been really hard to do. It's only been the last 20 years or so that we've moved beyond mailing things with the postal service. Being able to email and get feedback on files through track changes was a huge step forward, but it comes with a lot of bookkeeping and reproduciblity issues (did I do my analyses with `thesis_final_final.xls` or `thesis_final_usethisone.xls`?). But now, open tools make it much easier to collaborate. 

Working with collaborators in mind is critical for reproducibility. And, your most important collaborator is Future You. This training will introduce best practices using open tools, so that collaboration will become second nature to you!

## By the end of the course...

By the end of the course, you'll wrangle a few different data sets, and make your own graphics that you'll publish on webpages you've built collaboratively with GitHub and RMarkdown. Woop!



<!---
## Motivation 


More often than not, there are more than one way to do things. I'm going to focus mostly on what I have ended up using day-to-day; I try to incorporate better practices as I come upon them but that's not always the case. RStudio has some built-in redundancy too that I'll try to show you so that you can approach things in different ways and ease in.

- based on literature: best and good enough practices
- also based on our team's experience of how to do better science in less time




## Collaboration

Everything we learn today is to going to help you collaborate with your most important collaborator — YOU. Science is collaborative, starting with Future You, your current collaborators, and anyone wanting to build off your science later on. 

## Reproducibility

- record of your analyses. 
- rerun them!
- modify them, maybe change a threshold, try a different coefficient, etc, maybe today
- modify them, make a new figure, in 6 months! 

## Mindset

New but will become increasingly familiar. We’ll start you off with some momentum, like if you were going to learn to ride a bike or ...

Expect that there is a way to do what you want to do

- stop confounding data science with your science. Expect that someone has had your problem before or done what you want to do. 


If you plan to program mostly in one particular language on a single platform (such as Mac or Windows), you might try an integrated development environment (IDE). IDEs integrate text editing, syntax highlighting, version control, help, build tools, and debugging in one interface, simplifying development. 

http://r-bio.github.io/intro-git-rstudio/

## Data science is a discipline

It has theories, methods, and tools. 

Tidyverse and Hadley’s graphic. Tidy data.

Going to teach you how to think differently, get into some of the theory but in the context of hands-on work.


--->

