# Openscapes Mindset {#mindset}

Intro...

There are going to be a lot of "as"...

## Future you as your most important collaborator

Science is collaborative. In the big picture, you're contributing to how we understand and interact with the natural world. In a narrower sense, 

Collaborating efficiently has historically been really hard to do. It's only been the last 20 years or so that we've moved beyond mailing things with the postal service. Being able to email and get feedback on files through track changes was a huge step forward, but it comes with a lot of bookkeeping and reproduciblity issues (did I do my analyses with `thesis_final_final.xls` or `thesis_final_usethisone.xls`?). But now, open tools make it much easier to collaborate. 

Working with collaborators in mind is critical for reproducibility. And, your most important collaborator is Future You. This training will introduce best practices using open tools, so that collaboration will become second nature to you!


## Data science as a discipline

- analysis_final_v2.xlsx
- Re:FWD:Fwd:Data question
- your science is not unique when it comes to data
- expect there is a way to do what you want to do

There are concepts, theory, and tools for thinking about and working with data
Emphasis on communication
Not just for “big data”
Your study system is not unique when it comes to data


## Open science as a mindset/ Openness as a XXX

- not only about sharing your data

    
## Lab members as a team

Science is collaborative. 

- data & workflows lab meeting “nuts and bolts”

## Communities for learning, teaching, and mentorship

    
## The Internet as an underleveraged tool for science




<!---
- how to THINK about data 
    - how to think about data separately from your research questions
    - how and why to tidy data and analyze tidy data, rather than making your analyses accommodate messy data
    - how there is a lot of decision-making involved with data analysis, and a lot of creativity
- how to increase efficiency in your science
    - and increase reproducibility
    - and facilitate collaboration with others — especially Future You!
- how open science is a great benefit
    - find solutions faster
    - broaden the impact of your work
- how to learn with intention and community
    - think ahead instead of only to get a single job done now
    - the #rstats online community is fantastic. The tools we're using are developed by real people. Real, nice people. They are building powerful and empowering tools and are welcoming to all skill-levels
--->




<!---

Motivation 


More often than not, there are more than one way to do things. I'm going to focus mostly on what I have ended up using day-to-day; I try to incorporate better practices as I come upon them but that's not always the case. RStudio has some built-in redundancy too that I'll try to show you so that you can approach things in different ways and ease in.

- based on literature: best and good enough practices
- also based on our team's experience of how to do better science in less time




Collaboration

Everything we learn today is to going to help you collaborate with your most important collaborator — YOU. Science is collaborative, starting with Future You, your current collaborators, and anyone wanting to build off your science later on. 

 Reproducibility

- record of your analyses. 
- rerun them!
- modify them, maybe change a threshold, try a different coefficient, etc, maybe today
- modify them, make a new figure, in 6 months! 

Mindset

New but will become increasingly familiar. We’ll start you off with some momentum, like if you were going to learn to ride a bike or ...

Expect that there is a way to do what you want to do

- stop confounding data science with your science. Expect that someone has had your problem before or done what you want to do. 


If you plan to program mostly in one particular language on a single platform (such as Mac or Windows), you might try an integrated development environment (IDE). IDEs integrate text editing, syntax highlighting, version control, help, build tools, and debugging in one interface, simplifying development. 

http://r-bio.github.io/intro-git-rstudio/

 Data science is a discipline

It has theories, methods, and tools. 

Tidyverse and Hadley’s graphic. Tidy data.

Going to teach you how to think differently, get into some of the theory but in the context of hands-on work.


--->

