# Resources that influence us {#resources-influence} 

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(htmltools)
```

*Some resources that influence our thinking.*

<!---
# Innovation through openness, architecture, leadership, teamwork, and disruption

\*Openness and design is always on my mind, through Openscapes and beyond. But as a scientist, my entryway to it all has been through open science - more specifically/narrowly through data and code - so I am constantly learning of established ideas and stories from leaders of all kinds that inform and inspire me. I think differently now - more actively, optimistically, and boldly - than I did before, and am always trying to connect and reinforce ideas, tools, people, communities that I come across. Kindness is a big part of this too - I tried articulating some of these thoughts in my essay "Open software means kinder science" in [[Scientific American](%5Bhttps://blogs.scientificamerican.com/observations/open-software-means-kinder-science/)](<https://blogs.scientificamerican.com/observations/open-software-means-kinder-science/>)) at the end of my Mozilla Fellowship, but I have a lot more to learn. The plan here is to summarize things I've read and been thinking about along these lines. I highly recommend everything I list here and hope it will be inspiring for you too.\*

Welcoming entryways

I've always talked about Openscapes centered on the "what" : getting jazzed about open data science. But during COVID i've been focusing on the "how": 
and welcoming entryways

- new coders to R and collaborative, reproducible and open practices
- seasoned coders to GitHub
- scientists to open science through data science and publishing
- meeting design

Openscapes not just environmental science. Our roots are here with the community that we grew up with but it is much more. Mozilla. 


**Leaderful organizations**

We should be nurturing and empowering leaderful teams in science - this means horizontal leadership no matter your career stage


Jai: Electricity the cultural adaptation took a long time

Self-Organising System - Extinction Rebellion

--->
## Talking about data science: Hilary Parker & Roger Peng

[RStudio::conf(2020) keynote](https://rstudio.com/resources/rstudioconf-2020/not-so-standard-deviations-episode-100/) & [NSSD podcast episode 100]( http://nssdeviations.com/100-live-from-rstudio-conf-2020)

> If you want to write, you read a lot, music, you listen a lot. I'ts hard to do this with data analysis.

## Opinionated data analysis


## Principles for data analysis workflows
Stoudt, Vásquez, Martinez, 
https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008770

> workflow describes what a researcher does to make advances on scientific ques- tions: developing hypotheses, wrangling data, writing code, and interpreting results.
> Workflow: The process that moves a scientific investigation from raw data to coherent research question to insightful contribution. This often involves a complex series of pro- cesses and includes a mixture of machine automation and human intervention. It is a nonlinear and iterative exercise.

> Importantly, the difficulties we encounter in this [Explore] phase help us build empathy for an eventual audience beyond ourselves. It is here that we experience firsthand the challenges of processing our data set, framing domain research questions appro- priate to it, and structuring the beginnings of a workflow. Documenting our trial and error helps our own work stay on track in addition to assisting future researchers facing similar challenges.

## Vulnerability: Brené Brown

[Power of Vulnerability: TED Talk](https://www.ted.com/talks/brene_brown_the_power_of_vulnerability?language=en)

[Dare To Lead Podcast](https://brenebrown.com/dtl-podcast/)

### Hedgehog concept: Jim Collins

[Hedgehog concept](https://www.jimcollins.com/concepts/the-hedgehog-concept.html)


## All We Can Save: Ayana Johnson & Katharine Wilkinson

[All We Can Save Project](https://www.allwecansave.earth/)

> There is a renaissance blooming in the climate movement: leaderhip that is more characteristically feminine and more faithfully feminist, rooted in ompassion, connection, creativity, and collaboration. ...To change everything, we need everyone — All We Can Save

> Johnson’s frustration with the climate movement isn’t about the current leaders doing a bad job—it’s just that we need more leaders. Her vision of the world includes people from every community in climate leadership roles. — [The Marine Biologist Building an Inclusive Climate Movement](https://www.vice.com/en/article/5dpyn3/the-marine-biologist-building-an-inclusive-climate-movement), Vice

>All We Can Save is basically a community bound between two covers, and a gift to any who wishes to join in. - [Eric Roston, Bloomberg](https://www.bloomberg.com/news/articles/2020-12-22/this-book-about-climate-change-will-give-you-hope)


## The Power of Welcome 

[The Value of Welcome](https://ropensci.org/blog/2017/07/18/value-of-welcome/) — Stef Butland, rOpenSci

## The moment of lift: Melinda Gates

## Architecture of Participation: Tim O'Reilly

[It's Not About You: The Truth About Social Media Marketing](https://www.linkedin.com/pulse/20121002122119-16553-it-s-not-about-you-the-truth-about-social-media-marketing) (2012). Strategy on community building through modern channels

> "We tell big stories that matter to a community of users, and together we use those stories to amplify a message that we all care about...And once they start telling their story as part of the bigger story, it suddenly looks like a parade."

[Open source paradigm shift](https://www.oreilly.com/pub/a/tim/articles/paradigmshift_0504.html)

> I've come to use the term "the architecture of participation" to describe the nature of systems that are designed for user contribution.

## The Cathedral and the Bazaar: Eric Raymond


[The Cathedral and the Bazaar](https://www.oreilly.com/library/view/the-cathedral/0596001088/ch02.html#catbmain): one of the secrets of open source is "treating your users as co-developers"


## Systems Change: Donella Meadows 

[Leverage points: places to intervene in a system](http://donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system/): (in increasing order of effectiveness)

12. Constants, parameters, numbers (such as subsidies, taxes, standards).
11. The sizes of buffers and other stabilizing stocks, relative to their flows.
10. The structure of material stocks and flows (such as transport networks, population age structures).
9. The lengths of delays, relative to the rate of system change.
8. The strength of negative feedback loops, relative to the impacts they are trying to correct against.
7. The gain around driving positive feedback loops.
6. The structure of information flows (who does and does not have access to information).
5. The rules of the system (such as incentives, punishments, constraints).
4. The power to add, change, evolve, or self-organize system structure.
3. The goals of the system.
2. The mindset or paradigm out of which the system — its goals, structure, rules, delays, parameters — arises.
1. The power to transcend paradigms.


> So how do you change paradigms? Thomas Kuhn, who wrote the seminal book about the great paradigm shifts of science,7 has a lot to say about that. In a nutshell, you keep pointing at the anomalies and failures in the old paradigm, you keep coming yourself, and loudly and with assurance from the new one, you insert people with the new paradigm in places of public visibility and power. You don’t waste time with reactionaries; rather you work with active change agents and with the vast middle ground of people who are open-minded.


## Organizational architecture 

[Cautionary Tales Podcast Ep 6 -- How Britain Invented, Then Ignored, Blitzkrieg](http://timharford.com/2019/12/cautionary-tales-ep-6-how-britain-invented-then-ignored-blitzkrieg/). 

This tale is about how the organizational architecture of existing entities - whether the British army, Sony, Kodak, or Xerox - cannot always support their own innovation because of the social structures they were built upon. Fascinating to think about in terms of how open science has not been embraced by scientific communities within the existing academic structure.


## Disruption can feed creativity 

[Cautionary Tales Podcast Ep 7 -- Bowie, jazz, and the unplayable piano](http://timharford.com/2019/12/cautionary-tales-ep-7-bowie-jazz-and-the-unplayable-piano/). 

This tale is about music: how Keith Jarrett reluctantly played on a broken piano and how David Bowie and Brian Eno's take on collaboration led to brand new sounds and ideas. I think about this for science and openness - working out of your comfort zones and mixing up how you do it and who you do it with.

## Kaitlyn Thaney

[Funding research infrastructure](https://www.force11.org/blog/infrastructure-series-funding-research-infrastructure)

>there’s also the fact that the current funding model has led to a perceived sense of scarcity, pushing open projects to compete rather than collaborate, to build new features instead of maintaining their work and deepening their level of service for their communities. 
>An additional dimension to our work involves looking at the staffing and human infrastructure powering open technology development, maintenance, governance and stewardship. That volunteer labor and community engagement is often an invisible cost we gloss over in our estimations and recommendations, while also being a core pillar in this work.


<!---
**Science as behaviour: Using a behaviour change approach to increase uptake of open science**
Emma Norris & Daryl B. O’Connor
To cite this article: Emma Norris & Daryl B. O’Connor (2019) Science as behaviour: Using a behaviour change approach to increase uptake of open science, Psychology & Health, 34:12, 1397-1406, DOI: 10.1080/08870446.2019.1679373
To link to this article: https://doi.org/10.1080/08870446.2019.1679373

Focused on the behavior changes and interactions needed at the level of J, journals/publishers, F, funders, I, institutions, R, researchers.

Behavior Change Wheel (specifiaclly COM-B) posits three essential conditions as required to result in a behaviour (Michie et al., 2011): 

1. ‘capability’ in the individual’s psychological and physical capacity to enact a behaviour
1. ‘opportunity’ in the physical and social environment beyond the individual that allow a behaviour
1. ‘motivation’ in the reflective and automatic mechanisms that activate or inhibit a behaviour 

Another possibility might be to develop a Volitional Help Sheet for Open Science (VHS-OS; Armitage, 2008). The VHS technique is a simple technique that has been developed to help facilitate the forma- tion of if-then plans (or implementation intentions). This technique has been shown to be effective by encouraging respondents to actively form plans that help overcome salient barriers to engaging in a range of behaviours (Armitage, 2008; Armitage & Arden, 2012; O’Connor, Armitage, & Ferguson, 2015). Therefore, this might represent another fruitful way forward.

https://www.cos.io/blog/open-science-is-a-behavior
--->

## Mentorship vs Sponsorship

https://larahogan.me/sponsors/

