---
title: Teams and Pathways
---

One thing that makes Openscapes Champions Cohorts impactful is a focus on **teamwork**. People most often sign up as teams, with varying skillsets and responsibilities, perhaps with a shared project and perhaps not. People can also sign up as individuals. Some Champions have said that “finding their teams” during the cohort – finding what’s common and feeling less alone while learning skills with their peers – has been the most valuable part of Openscapes.

Openscapes Champions was originally designed with academic research groups in mind, to provide resilience where there is high turnover and folks might be struggling with similar challenges around data analysis while working on different projects. But we're increasingly working with research groups of different kinds and needs, some producing big annual reports or indicators! We expect a range of technical ability and training experience; most importantly is selecting folks that have interest in making daily practices more efficient and developing collaboration and leadership skills.

## Teams: frequently asked questions 

### How many people participate?

The Champions Program operates as cohorts of 7-10 teams of up to 5 people; 40 people max in the cohort. 

### Why do people join a Champions cohort? 

People join because they (as an individual or team):

- Want to learn about or work with open Science
- Want to meet peers working on similar workflow or data issues
- Have a ‘big goal’ that involves changing how you work; you want to make progress on making your data and science workflows more efficient and reproducible

### What is a team? 

There is a lot of flexibility in choosing your team.

Teams do not need to be a formal research group; they can be collaborating in other ways. Team members do not all need to have technical or data interests, but share a curiosity and interest in improving something about how they work. Participants are expected to have ‘Seaside Chats’ together with their broader research groups in the weeks between Cohort Calls, so it is OK, and expected, that only a subset of a team participate.

### What skills are required? Coding? GitHub?

No. This is not a coding workshop. 

The purpose is strengthen relationships and shared systems with folks with different responsibilities and skills, so there is less reinventing and less knowledge lost.

During the cohort, people focus on what is important to them, often something hard to do, something they want to change. Throughout the cohort, as Openscapes introduces modern concepts, tooling, and peer examples, people learn together and get unstuck through identifying and making progress on barriers. Each cohort call (90 minutes) has 30-40 minute of lessons and the rest of the time is you reflecting and discussing how this could help you with your own work.


### How do I choose my team?

Choosing your team can be based on interests around data analysis and around leadership. There are no prerequisite skills to participate, just an interest to learn and contribute. The "homework" between Champions sessions and beyond is to meet with your full research group (beyond workshop participants, and optional for the lead) to establish shared workflows and habits within the research group.

>*How you define \"team\" is completely up to you and having one person be in the cohort and using in-between session \"seaside chats\" to bring back the information to another group is 100% fine. That is common in the cohorts. In my first Openscapes cohort, I was the only person from my project. My personal goal was to use the Openscapes structure to help a team that I am on figure out how to tackle some off-boarding tasks due to a retirement. During my second cohort, there were 2 team members in the cohort and 2 not in the cohort. We focused on standardizing our data to get ready for our GitHub served data package. For the 3rd cohort I am doing, ^2^⁄~3~ of our team is in the cohort as we start to get organized for a major revamp of our report into a reproducible workflow.* **- Eli Holmes (NOAA NWFSC, NMFS-Openscapes)**

### What if I don’t have a team?

That’s ok, please sign up! We’ll help you connect with participants who share some of your goals or needs.

<!---
The Champions Program is structured for teams with the intent that research group leads (faculty, lecturers, program managers, etc) and members (students, post-docs, analysts, lab managers, etc.) participate as a team together. This is a strategy so that the lead does not necessarily have to be an expert/comfortable with open data science to enable their team to design open data science workflows. Group leads and members participate together so that:

1.  everyone sees and values what is possible for their work
2.  leads enable members to invest time in learning skills and developing shared workflows as part of their jobs
3.  members have guidance, agency, and support to incorporate open data science concepts into their work
4.  everyone champions open science and contributes to growing the community of practice within the research group, institution, and beyond, in whatever capacity their roles and circumstances (time limitations & responsibilities) allow.
--->

### Does a team need a shared research project?

No, teams do not need to have a specific shared research project to participate. 

The idea is that by developing shared open data science habits within the research group, it will be easier to onboard new folks and offboard knowledge/data/code/etc when folks leave. And, as more and more research groups work this way, it can ease transitions between research groups (i.e. when students graduate and take a position with a different research group).

### Is attendance required for all Cohort Calls?

Yes; we do try to have everyone on the team attend all Cohort Calls – but know that sometimes that’s not possible. All the lessons, slides, and also recordings are available if people have to miss, but everyone should sign up expecting to be at the Cohort Calls.

### Do I as the PI need to attend the Cohort Calls, or just my team?

It’s important that team leads attend with their team. The Champions program is designed to reduce the burden for PIs in the long term and develop leadership within and across their teams. With this investment now, team leads and members will build resilient and enduring practices for their research group, even as that research group changes into the future. The idea is that together, the whole team sees what’s possible with open data science and builds confidence, ownership, and a shared pathway forward. Then it’s the entire team, not just the PI, who puts it to practice in between sessions.

## CHAMPIONS PROGRAM: COHORTS

### Does a cohort need a shared research project or to be closely related?

No, the cohort does not need a shared project; each team will work on what they need to for their own research. Teams within a cohort do not need to be closely related, but having teams somewhat related is good for community building (i.e. environmental science or psychology).

### Can we have smaller teams so more teams can participate in a cohort?

From our experiences so far think that ~8 teams with 4-5 participants per team (maximum of ~40 participants) is a good size so there is time for everyone to be engaged and contributing (and not feeling like a passive webinar). Also, having a good amount of members per team is really key to the whole model of Openscapes: we want to reduce the amount of burden for PIs to have to relay info to their research groups. Having more members participate as a team in the Openscapes program helps more team members feel agency to build resilient systems with less transmission time.

> “I didn’t think to find solutions, because I didn’t realize that there was a problem; I thought that this was just the nature of doing [ecological] research – an endless pile of confusingly named csv files and R scripts....Now that I can see all the ways that our lab has profited from this initial investment, I cannot imagine how I managed without Openscapes’ principles. Our lab is producing substantially more science of higher quality and we are making more of our underlying data and code publicly available as a direct result of Openscapes’ intervention.” -
Dr. Chelsea Wood, University of Washington

