---
title: "Do and fix things in Git"
---

These are our go-to resources about GitHub; they include philosophy, step-by-step guidance, and troubleshooting. Most examples are with R and RStudio, and are applicable more broadly.

## Excuse Me, Do You Have a Moment to Talk About Version Control?

"[Excuse Me, Do You Have a Moment to Talk About Version Control](https://peerj.com/preprints/3159/)?" Bryan J, 2017, PeerJ 

## Happy Git With R

> "Happy Git provides opinionated instructions on how to Install Git and get it working smoothly with GitHub, in the shell and in the RStudio IDE; Develop a few key workflows that cover your most common tasks; Integrate Git and GitHub into your daily work with R and R Markdown."

<https://happygitwithr.com/>

## R for Excel Users

[R for Excel Users](https://rstudio-conf-2020.github.io/r-for-excel/). Lowndes J and Horst A, 2020. Chapter 4 and 8 focus on starting setup and collaboration with GitHub and RStudio

## `usethis`

[usethis](https://usethis.r-lib.org/). Wickham H and Bryan J.

> usethis is a workflow R package: it automates repetitive tasks that arise during project setup and development, both for R packages and non-package projects.

## Git Flight Rules

"A guide for astronauts (now, programmers using Git) about what to do when things go wrong."

<https://github.com/k88hudson/git-flight-rules>

This is quite a comprehensive and maintained list of git commands, using the command line.

## GitHub: A beginner's guide to going back in time (aka fixing mistakes)

<https://ohi-science.org/news/github-going-back-in-time>

This has screenshots and a workflow with RStudio and the command line.
