---
title: "Discuss open science and community building"
---

Conversations about community building and open science is really important for getting support and supporting others with this work.

```{=html}
<!---

Open Science

Curated resources from:

https://nna-co.org/strategic-objectives/open-science


https://onlinelibrary.wiley.com/doi/10.1002/ajs4.141

https://indigenous-data-envs-2022.netlify.app/index.html

https://knowledgeequitylab.ca/podcast/ --- https://knowledgeequitylab.ca/podcast/s2ep4/

--->
```
## Community building

How do you talk to others (managers, supervisors) about the importance of community building and building social infrastructure? Here are some starting resources for reading about community building with Openscapes.

They are in order of article length and increasing specificity:

-   [Shifting institutional culture to develop climate solutions with Open Science](https://onlinelibrary.wiley.com/doi/10.1002/ece3.11341) (Lowndes et al 2024) - An Open Access Editorial written collaboratively by Mentors across the Openscapes community

-   [Supercharge your research: a ten-week plan for open data science](https://openscapes.github.io/supercharge-research/) (Lowndes et al 2019) - community building within teams, based on our flagship program Openscapes Champions


    -   These slides - [Documenting things: openly for future us](https://openscapes.github.io/documenting-things) share what's possible from focusing on documentation and community

-   [The Openscapes Flywheel: A framework for managers to facilitate and scale inclusive Open science practices](https://eartharxiv.org/repository/view/4560/) (Robinson & Lowndes 2022) - community building within NASA with a framework we developed and refine. 

    -   These [slides from an internal NASA meeting in March 2023](https://docs.google.com/presentation/d/14iEGfbipt5HBlVyyf3kvjyxas4lBoRlbT8u8iFr2VNw/edit#slide=id.g1b5922f14f8_0_83) (linked from [openscapes.org/media](http://openscapes.org/media)) tell some of this story
