---
title: "Setup RStudio and GitHub"
---

## Installation
To setup RStudio and GitHub, you will need four things: 

1. R
1. RStudio
1. Git
1. GitHub

Follow the [UCSB MEDS Installation Guide](https://ucsb-meds.github.io/meds-install-guide.html) for detailed instructions on how to create accounts, download, install, and configure on Mac and Windows. (For an even more detailed walk-through, see [Allison Horst's ESM 206 Google Doc](https://docs.google.com/document/d/1zx2upJJqFZe94O3BQSMI56Z76s3haLXC0otKSpcZaJQ/edit)). Thanks for sharing Allison!

## Practice

### Learn R interactively

[swirl](https://swirlstats.com/) lets you learn R, in R.

swirl teaches you R programming and data science interactively, at your own pace, and right in the R console!

It's developed by [Sean Kross](https://seankross.com/), who also co-created the [Tidy Data Tutor](https://tidydatatutor.com/)

### R and GitHub together

Now you'll want to practice how to use RStudio and GitHub. Follow [R for Excel Users' GitHub Chapter](https://rstudio-conf-2020.github.io/r-for-excel/github.html) to create a GitHub repository, clone it to RStudio, make edits, and practice syncing. 
