---
title: Pathways
---

## The idea

Perhaps the most important part of Openscapes is helping teams identify their trailhead together, as illustrated in the Champions [landscape illustration](/index.qmd#welcome). We support individuals to "find their teams" by discussing approaches and software, so that they find they have common parts of how they work, whether they are working on the same or different projects.

The Pathways Spreadsheet provides a structured way for your team to think how you work and find common approaches and needs ([template](https://docs.google.com/spreadsheets/d/1X_-qPdWDCpw2F3nZr6vZnq87guyUIGLvekm0XV2H-A8/edit#gid=0))

This format has helped many groups think through their trailhead and identifying where they are now. It also might not work for your group, and that is okay; use whatever format makes sense for you.

## Presenting guidance

On the final Cohort Call, each team presents their Pathways. Each team has 3 minutes to share followed by 2 minutes for questions. We encourage leads not to present, and it's great when we hear multiple voices from the teams.

**This is informal sharing of unpolished work-in-progress.** Everyone makes progress throughout the Cohort: in mindsets, planning and actions. This is an opportunity to reflect and talk about it, building on the reflection breakout rooms that began most Cohort Calls. We've been reflective each week and we've all made progress.

Presentations do not need be line-by-line of the Pathways Spreadsheet and there's no wrong way to talk about your progress. Whatever your group wants to create and share is great - could be a photo of a whiteboard, a slide, the Pathways spreadsheet, or a "screenshare and tell" live walk-through of your files/code/ideas.

A few reflection prompts that can help frame the presentations:

-   What are the practices we've covered during the Cohort that most compel you?
-   What are the practices we've covered this semester that most confuse you?
-   Are there practices that are new to you that you didn't originally think would work with your own research interests? If so, which?
-   What are your two biggest take-aways from the Cohort?
-   What future revisions will you propose making for your pathway
-   Any final questions you want to workshop with the Cohort?

## Examples

![An example of an Openscapes pathway written by the NOAA Alaska Fisheries Science Center EcoFOCI team. The diagram summarizes how they used to share code, data, and files, and what their ongoing plans are for streamlining these processes and creating a team culture of openness and psychological safety.](images/afsc-ecofoci.png)

See more examples:

-   [A TL;DR Collection of Stories from Openscapes Champions and Mentors](https://docs.google.com/presentation/d/1YAnaRFsKX3H6cSTXoOl-GksH-eebifQ6vzN7UwfoXUY/edit?usp=sharing); these stories are largely from 3 months+ following Pathways presentations
-   [**Case Studies**](https://www.openscapes.org/tags/case-study/) from the inaugural Champions Cohort (2021)
